export const ADD_POST = 'ADD_POST'
export const EDIT_POST = 'EDIT_POST'
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_POST = 'GET_POST'
export const VOTE_POST = 'VOTE_POST'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
